name: azure-dev

on:
  workflow_dispatch:
    inputs:
      cleanup-resources:
        description: "Clean up resources after deployment"
        required: false
        default: true
        type: boolean
  pull_request:
    # Also trigger on ready_for_review to catch the transition from draft to ready state.
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main
    paths:
      - ".github/workflows/azure-dev.yml"
      - "infra/**"
      - "tests/IntegrationTests/**"
      - "azure.yaml"
      - "bicepconfig.json"

defaults:
  run:
    shell: pwsh # Use PowerShell Core for all scripts (the azd hooks are written in PowerShell)

env:
  # Add a unique suffix to the environment name for pull requests to avoid name conflicts
  AZURE_ENV_NAME: ${{ github.event.pull_request.number && format('{0}-pr{1}', vars.AZURE_ENV_NAME, github.event.pull_request.number) || vars.AZURE_ENV_NAME }}
  AZURE_LOCATION: ${{ vars.AZURE_LOCATION }}
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID || vars.AZURE_SUBSCRIPTION_ID }}
  AZURE_API_MANAGEMENT_SKU: ${{ vars.AZURE_API_MANAGEMENT_SKU || 'BasicV2' }}
  INCLUDE_APPLICATION_GATEWAY: ${{ vars.INCLUDE_APPLICATION_GATEWAY || 'true' }}
  AZURE_APPLICATION_GATEWAY_MTLS_MODE: ${{ vars.APPLICATION_GATEWAY_MTLS_MODE || 'Strict' }}
  VALIDATE_CERTIFICATE_CHAIN_IN_PROTECTED_API: ${{ vars.VALIDATE_CERTIFICATE_CHAIN_IN_PROTECTED_API || 'false' }}

jobs:
  # ------------------------------------------------------------
  # Build, Verify and Package
  # ------------------------------------------------------------

  build-verify-package:
    name: Build, Verify and Package
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required to fetch an OIDC token for Azure authentication
      contents: read # Required to checkout code if needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup azd
        uses: Azure/setup-azd@v2

      - name: Setup .NET 10
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "10.0.x"

      - name: Print Tool Versions
        run: |
          az version
          az bicep version
          azd version
          Write-Host ".NET SDK Version: $(dotnet --version)"

      # Use Azure CLI authentication with azd commands so credentials are shared between azd commands and az (Azure CLI) commands used in hooks.
      - name: Configure azd to use Azure CLI Authentication
        run: |
          azd config set auth.useAzCliAuth "true"

      # Login to the Azure CLI with OpenID Connect (OIDC) using federated identity credentials.
      - name: Azure CLI Login
        uses: azure/login@v3
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID || vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID || vars.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID || vars.AZURE_SUBSCRIPTION_ID }}

      - name: Bicep Lint
        run: |
          az bicep lint --file ./infra/01-core/main.bicep
          az bicep lint --file ./infra/02-platform/main.bicep
          az bicep lint --file ./infra/03-application/main.bicep

      - name: Validate Core Layer Template
        run: |+
          az deployment sub validate `
            --template-file './infra/01-core/main.bicep' `
            --location $env:AZURE_LOCATION `
            --parameters environmentName=$env:AZURE_ENV_NAME `
                         location=$env:AZURE_LOCATION `
                         includeApplicationGateway=$env:INCLUDE_APPLICATION_GATEWAY `
                         applicationGatewayMtlsMode=$env:AZURE_APPLICATION_GATEWAY_MTLS_MODE `
                         apiManagementSku=$env:AZURE_API_MANAGEMENT_SKU `
                         validateCertificateChainInProtectedApi=$env:VALIDATE_CERTIFICATE_CHAIN_IN_PROTECTED_API

      - name: Validate Platform Layer Template
        run: |+
          az deployment sub validate `
            --template-file './infra/02-platform/main.bicep' `
            --location $env:AZURE_LOCATION `
            --parameters environmentName=$env:AZURE_ENV_NAME `
                         location=$env:AZURE_LOCATION `
                         instanceId='sample' `
                         resourceGroupName='sample' `
                         agwPublicIpAddressName='sample' `
                         appInsightsName='sample' `
                         keyVaultName='sample' `
                         logAnalyticsWorkspaceName='sample' `
                         apiManagementSku=$env:AZURE_API_MANAGEMENT_SKU `
                         applicationGatewayMtlsMode=$env:AZURE_APPLICATION_GATEWAY_MTLS_MODE `
                         includeApplicationGateway=$env:INCLUDE_APPLICATION_GATEWAY

      - name: Validate Application Layer Template
        run: |
          az deployment sub validate `
            --template-file './infra/03-application/main.bicep' `
            --location $env:AZURE_LOCATION `
            --parameters resourceGroupName='sample' `
                         apiManagementServiceName='sample' `
                         keyVaultName='sample' `
                         includeApplicationGateway=$env:INCLUDE_APPLICATION_GATEWAY `
                         validateCertificateChainInProtectedApi=$env:VALIDATE_CERTIFICATE_CHAIN_IN_PROTECTED_API

      - name: Create artifacts folder
        run: |
          mkdir -p ./artifacts

      - name: Build Integration Tests
        run: |
          dotnet build ./tests/IntegrationTests/IntegrationTests.csproj --configuration Release --output ./artifacts/integration-tests

      - name: Upload Integration Tests Package
        uses: actions/upload-artifact@v7
        with:
          name: integration-tests-package
          path: ./artifacts/integration-tests/
          retention-days: 1

  # ------------------------------------------------------------
  # Deploy to Azure
  # ------------------------------------------------------------

  deploy:
    name: Deploy to Azure
    needs: build-verify-package
    # Only deploy if it's not a pull request or if the pull request is ready for review (not a draft) to avoid deploying from work-in-progress branches.
    if: github.event_name != 'pull_request' || github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required to fetch an OIDC token for Azure authentication
      contents: read # Required to checkout code if needed

    outputs:
      AZURE_API_MANAGEMENT_GATEWAY_URL: ${{ steps.get-outputs.outputs.AZURE_API_MANAGEMENT_GATEWAY_URL }}
      AZURE_APPLICATION_GATEWAY_PUBLIC_IP_ADDRESS_VALUE: ${{ steps.get-outputs.outputs.AZURE_APPLICATION_GATEWAY_PUBLIC_IP_ADDRESS_VALUE }}
      AZURE_KEY_VAULT_URI: ${{ steps.get-outputs.outputs.AZURE_KEY_VAULT_URI }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup azd
        uses: Azure/setup-azd@v2

      # Use Azure CLI authentication with azd commands so credentials are shared between azd commands and az (Azure CLI) commands used in hooks.
      - name: Configure azd to use Azure CLI Authentication
        run: |
          azd config set auth.useAzCliAuth "true"

      # Login to the Azure CLI with OpenID Connect (OIDC) using federated identity credentials.
      - name: Azure CLI Login
        uses: azure/login@v3
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID || vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID || vars.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID || vars.AZURE_SUBSCRIPTION_ID }}

      - name: Provision Infrastructure
        run: |
          azd provision --no-prompt --no-state

      # Extract relevant azd environment variables and make them available as job outputs for subsequent jobs.
      - name: Get Output Variables
        id: get-outputs
        run: |
          $variableNames = @(
            "AZURE_API_MANAGEMENT_GATEWAY_URL",
            "AZURE_APPLICATION_GATEWAY_PUBLIC_IP_ADDRESS_VALUE",
            "AZURE_KEY_VAULT_URI"
          )
          .\.github\workflows\scripts\export-azd-env-variables.ps1 -VariableNames $variableNames

  # ------------------------------------------------------------
  # Verify Deployment
  # ------------------------------------------------------------

  verify-deployment:
    name: Verify Deployment
    needs: deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required to fetch an OIDC token for Azure authentication

    steps:
      - name: Setup .NET 10
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "10.0.x"

      - name: Download Integration Tests Package
        uses: actions/download-artifact@v8
        with:
          name: integration-tests-package
          path: ./artifacts/integration-tests

      # Login to the Azure CLI with OpenID Connect (OIDC) using federated identity credentials.
      # This is necessary for the integration test to access Azure resources if needed.
      - name: Azure CLI Login
        uses: azure/login@v3
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID || vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID || vars.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID || vars.AZURE_SUBSCRIPTION_ID }}

      - name: Run Integration Tests
        run: |
          dotnet ./artifacts/integration-tests/IntegrationTests.dll --report-trx --results-directory ./artifacts/integration-tests/TestResults
        working-directory: ./
        env:
          # Pass the necessary deployed resource properties as environment variables so the integration tests can access them.
          AZURE_API_MANAGEMENT_GATEWAY_URL: ${{ needs.deploy.outputs.AZURE_API_MANAGEMENT_GATEWAY_URL }}
          AZURE_APPLICATION_GATEWAY_PUBLIC_IP_ADDRESS_VALUE: ${{ needs.deploy.outputs.AZURE_APPLICATION_GATEWAY_PUBLIC_IP_ADDRESS_VALUE }}
          AZURE_KEY_VAULT_URI: ${{ needs.deploy.outputs.AZURE_KEY_VAULT_URI }}

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: integration-test-results
          path: ./artifacts/integration-tests/TestResults/
          retention-days: 1

  # ------------------------------------------------------------
  # Clean Up Resources
  # ------------------------------------------------------------

  cleanup:
    name: Clean Up Resources
    needs: [deploy, verify-deployment]
    if: ${{ success() && (github.event_name != 'workflow_dispatch' || github.event.inputs.cleanup-resources == 'true') }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required to fetch an OIDC token for Azure authentication
      contents: read # Required to checkout code if needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup azd
        uses: Azure/setup-azd@v2

      # Use Azure CLI authentication with azd commands so credentials are shared between azd commands and az (Azure CLI) commands used in hooks.
      - name: Configure azd to use Azure CLI Authentication
        run: |
          azd config set auth.useAzCliAuth "true"

      # Login to the Azure CLI with OpenID Connect (OIDC) using federated identity credentials.
      - name: Azure CLI Login
        uses: azure/login@v3
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID || vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID || vars.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID || vars.AZURE_SUBSCRIPTION_ID }}

      # Clean up using the --purge flag to ensure all resources are permanently deleted, like API Management.
      - name: Cleanup Resources
        run: |
          azd down --purge --force --no-prompt
